resources:
  - name: conan_gopigo_github
    type: GitRepo
    configuration:
      path: czoido/conan-gopigo
      gitProvider: czoido_github

pipelines:
  - name: conan_gopigo
    steps:
      - name: build_library
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: czoido/pipelines-conanio-gcc8-armv7hf
                tag: latest
                options: "-e HOME=/root"
          inputResources:
            - name: conan_gopigo_github
          integrations:
            - name: czoido_docker
        execution:
          onStart:
            - echo "Preparing for work..."
            - conan remote list
            - ls -l
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:
            - echo "Cleaning up some stuff"
