resources:
  - name: conan_gopigo_github
    type: GitRepo
    configuration:
      path: czoido/conan-gopigo
      gitProvider: czoido_github

pipelines:
  - name: conan_gopigo
    steps:
      - name: build_docker_image
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: art-yalla.jfrog-lab.com/docker-local/gopigo
          dockerImageTag: $run_number
          inputResources:
            - name: conan_gopigo_github
          integrations:
            - name: artifactory
      - name: push_docker_image
        type: PushArtifactoryPackage
        configuration:
          targetRepo: docker-local
          integrations:
            - name: artifactory
          inputSteps:
            - name: build_docker_image
      - name: build_gopigo_package
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: conan_gopigo
                tag: $run_number
          inputSteps:
            - name: push_docker_image
          integrations:
            - name: artifactory
        execution:
          onExecute:
            - ls -l
            - python build.py
      - name: print_information
        type: Bash
        configuration:
          inputSteps:
            - name: build_gopigo_package
        execution:
          onExecute:
            - ls -l
            - printenv
            - echo $res_conan_gopigo_github_commitSha          

