resources:
  - name: conan_gopigo_github
    type: GitRepo
    configuration:
      path: czoido/conan-gopigo
      gitProvider: czoido_github

pipelines:
  - name: conan_gopigo_pipeline
    steps:
      - name: build_library
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: conan_build_image
          dockerImageTag: $run_number
          inputResources:
            - name: conan_gopigo_github
          integrations:
            - name: czoido_docker

      - name: print_information
        type: Bash
        configuration:
          inputSteps:
            - name: build_library
        execution:
          onExecute:
            - ls -l
            - printenv
            - echo $res_conan_gopigo_github_commitSha          

