resources:
  - name: conan_gopigo_github
    type: GitRepo
    configuration:
      path: czoido/conan-gopigo
      gitProvider: czoido_github

pipelines:
  - name: conan_gopigo
    steps:
      - name: build_library
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: czoido/pipelines-conanio-gcc8-armv7hf
                tag: latest
          inputResources:
            - name: conan_gopigo_github
          integrations:
            - name: czoido_docker
        execution:
          onExecute:
            - pip install conan --upgrade
            - pip install conan_package_tools
            - git clone https://github.com/czoido/conan-gopigo.git
            - cd conan-gopigo
            - conan user
            - conan profile new default --detect
            - conan profile show default
            - conan profile update settings.compiler.libcxx=libstdc++11 default
            - conan profile update settings.compiler.version=8 default
            - python build.py
