resources:
  - name: conan_gopigo_github
    type: GitRepo
    configuration:
      path: czoido/conan-gopigo
      gitProvider: czoido_github

pipelines:
  - name: conan_gopigo
    steps:
      - name: build_docker_image
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: art-yalla.jfrog-lab.com:443/yalla-gopigo
          dockerImageTag: $run_number
          inputResources:
            - name: conan_gopigo_github
          integrations:
            - name: artifactory
      - name: test_step
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: golang
                tag: latest
          integrations:
            - name: czoido_docker
          inputSteps:
            - name: build_docker_image
        execution:
          onExecute:
            - ls -l
            - python build.py

